// Code generated by girgen. DO NOT EDIT.

package gi

/*
#cgo pkg-config: girepository-2.0
#include <girepository/girepository.h>
*/
import "C"

import (
	"structs"
	"unsafe"

	"deedles.dev/gir/g"
)

type AttributeIter struct {
	_ structs.HostLayout
	_ [40]byte

	// data

	// _dummy

}

func (s *AttributeIter) c() *C.GIAttributeIter {
	return (*C.GIAttributeIter)(unsafe.Pointer(s))
}

type BaseInfoStack struct {
	_ structs.HostLayout
	_ [96]byte

	// parent_instance

	// dummy0

	// dummy1

	// dummy2

	// dummy3

}

func (s *BaseInfoStack) c() *C.GIBaseInfoStack {
	return (*C.GIBaseInfoStack)(unsafe.Pointer(s))
}

type Typelib struct {
	_ structs.HostLayout
	_ [0]byte
}

func (s *Typelib) c() *C.GITypelib {
	return (*C.GITypelib)(unsafe.Pointer(s))
}

func TypelibNewFromBytes(bytes *g.Bytes) {
	panic("Not implemented.")
}

func (s *Typelib) GetNamespace() {

	C.gi_typelib_get_namespace(s.c())

}

func (s *Typelib) Ref() {

	C.gi_typelib_ref(s.c())

}

func (s *Typelib) Symbol(symbol_name string) (symbol unsafe.Pointer) {
	arg0 := C.CString(symbol_name)
	defer C.free(unsafe.Pointer(arg0))
	arg1 := (unsafe.Pointer)(symbol)
	C.gi_typelib_symbol(s.c(), arg0, &arg1)
	panic("Not implemented.")
}

func (s *Typelib) Unref() {

	C.gi_typelib_unref(s.c())

}
